import express from "express";
const router = express.Router();
import UserController from "./UserController";
import FeedController from "./FeedController";
import GroupChatController from "./GroupChatController";
import VoucherController from "./VoucherController";
import CrawlController from "./CrawlController";
import FeedRestrictionRuleController from "./FeedRestrictionRuleController";
import CategoryController from "./CategoryController";
import TaskController from "./TaskController";
import BlogController from "./BlogController";
import SupplierController from "./SupplierController";
import BrandController from "./BrandController";
import AdminUserController from "./AdminUserController";
import CouponCategoryController from "./CouponCategoryController";
import NotificationController from "./NotificationController";
import BannerFeedAdController from "./BannerFeedAdController";
import HashTagController from "./HashTagController";
import CouponAdController from "./CouponAdController";
import ProductFeedAdController from "./ProductFeedAdController";

router.use("/users", UserController);
router.use("/feeds", FeedController);
router.use("/feed-rules", FeedRestrictionRuleController);
router.use("/group-chats", GroupChatController);
router.use("/voucher", VoucherController);
router.use("/crawl", CrawlController);
router.use("/categories", CategoryController);
router.use("/tasks", TaskController);
router.use("/blogs", BlogController);
router.use("/suppliers", SupplierController);
router.use("/brands", BrandController);
router.use("/admins", AdminUserController);
router.use("/coupon-categories", CouponCategoryController);
router.use("/notifications", NotificationController);
router.use("/banner-feed-ads", BannerFeedAdController);
router.use("/hashtags", HashTagController);
router.use("/coupon-ads", CouponAdController);
router.use("/product-feed-ads", ProductFeedAdController);

export default router;
