const ServerEvents = {
    NEW_USER_JOIN_ROOM: "NEW_USER_JOIN_ROOM",
    ACCEPT_USER_JOIN_ROOM: "ACCEPT_USER_JOIN_ROOM",
    REJECT_USER_JOIN_ROOM: "REJECT_USER_JOIN_ROOM",
    USER_EXIT_ROOM: "USER_EXIT_ROOM",
    USER_TYPING: "USER_TYPING",
    USER_STOP_TYPING: "USER_STOP_TYPING",
    USER_POST_MESSAGE: "USER_POST_MESSAGE",
    CONFIRM_JOIN_ROOM: "CONFIRM_JOIN_ROOM",
    DATA_LOADING: "DATA_LOADING",
    HISTORY_LOADING: "HISTORY_LOADING",
    HISTORY_CHAT: "HISTORY_CHAT",
    AUTHENTICATED: "AUTHENTICATED",
    UNAUTHENTICATED: "UNAUTHENTICATED"
};

const ClientEvents = {
    USER_JOIN_ROOM: "USER_JOIN_ROOM", // Event on user join room chat
    USER_EXIT_ROOM: "USER_EXIT_ROOM", // Event on user exit room chat
    USER_TYPING: "USER_TYPING", // Event on user typing message
    USER_STOP_TYPING: "USER_STOP_TYPING",
    USER_POST_MESSAGE: "USER_POST_MESSAGE", // Event on user post new message
    AUTHENTICATE: "AUTHENTICATE"
};

export {
    ServerEvents,
    ClientEvents
};